#!/bin/bash
echo compiling...
NAME=`echo $1 | sed "s/\.[^\.]*$//"`
sudo g++ $1 -o $NAME -lwiringPi -pthread -std=c++11
echo complete!
echo ENTER to run
read WAIT
echo running...
cd `dirname $NAME`
sudo ./`basename $NAME`
